function setLevel (levelNumber: number) {
    scene.setBackgroundColor(1)
    currentLevel = levelNumber
    if (levelNumber == 1) {
        tiles.setTilemap(tilemap`level1`)
    } else if (levelNumber == 0) {
        tiles.setTilemap(tilemap`level3`)
    } else if (levelNumber == 0) {
        tiles.setTilemap(tilemap`level4`)
    } else {
        tiles.setTilemap(tilemap`level5`)
    }
}
sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    sprite.setBounceOnWall(true)
    sprite.setVelocity(60, 0)
})
function setRunner () {
    Runner = sprites.create(img`
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 
        `, SpriteKind.Player)
    controller.moveSprite(Runner)
    tiles.placeOnTile(Runner, tiles.getTileLocation(0, 1))
    scene.cameraFollowSprite(Runner)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    currentLevel += 1
    setLevel(currentLevel)
})
function setEnemy (levelNumber: number) {
    if (levelNumber == 1) {
        mazeEnemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        mazeEnemy2 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        mazeEnemy3 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnTile(mazeEnemy, tiles.getTileLocation(9, 6))
        tiles.placeOnTile(mazeEnemy2, tiles.getTileLocation(3, 10))
        tiles.placeOnTile(mazeEnemy3, tiles.getTileLocation(11, 8))
    } else {
    	
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    Runner.destroy()
    game.over(false)
})
let mazeEnemy3: Sprite = null
let mazeEnemy2: Sprite = null
let mazeEnemy: Sprite = null
let Runner: Sprite = null
let currentLevel = 0
setLevel(1)
setEnemy(1)
setRunner()
