sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    Enemy1.sayText("" + text_list[randint(0, text_list.length - 1)])
    pause(100)
    Runner.destroy()
    pause(1000)
    game.over(false)
})
let text_list: string[] = []
let Enemy1: Sprite = null
let Runner: Sprite = null
Runner = sprites.create(img`
    . . . . . . 2 . . . . 2 . . . . 
    . . . . . 5 5 5 . . 5 5 5 . . . 
    . . . . 4 4 4 4 4 4 4 4 4 . . . 
    . . . 8 8 8 8 8 8 8 8 8 8 . . . 
    . . 8 8 8 f 8 8 8 8 f 8 8 . . . 
    . 8 8 8 8 8 8 8 8 8 8 8 8 . . . 
    8 8 8 2 8 8 8 8 8 2 8 8 8 . . . 
    8 8 8 2 2 2 2 2 2 2 8 8 8 . . . 
    . 8 8 8 8 8 8 8 8 8 8 8 8 . . . 
    . 8 8 8 8 8 8 8 8 8 8 8 8 . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    . . 8 8 8 . . . . 8 8 8 . . . . 
    `, SpriteKind.Player)
Runner.setPosition(35, 58)
controller.moveSprite(Runner)
Enemy1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . b 5 5 b . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 b . 
    b d d c d 5 5 b 5 4 4 4 4 4 4 b 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Enemy)
text_list = [
"L",
"Practice More",
"Bye",
"Can't Touch This",
"Adios"
]
function setLevel(levelNumber: number) {
    scene.setBackgroundColor(1)
    currentLevel = levelNumber
    if (levelNumber == 1) {
        tiles.setTilemap(tilemap`level1`)
    } else if (levelNumber == 0) {
        tiles.setTilemap(tilemap`level3`)
    } else if (levelNumber == 0) {
        tiles.setTilemap(tilemap`level4`)
    } else {
        tiles.setTilemap(tilemap`level5`)
    }
}
sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    sprite.setBounceOnWall(true)
    sprite.setVelocity(50, 0)
})
function setRunner() {
    Runner = sprites.create(img`
        . . . . . 2 2 2 2 2 2 2 . . . . 
        . . . 2 2 2 2 2 2 2 2 2 2 2 . . 
        . . 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . . 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        . . 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . . 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
        . . . 2 2 2 2 2 2 2 2 2 2 2 . . 
        . . . . . 2 2 2 2 2 2 2 . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Player)
    controller.moveSprite(Runner)
    tiles.placeOnTile(Runner, tiles.getTileLocation(0, 1))
    scene.cameraFollowSprite(Runner)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    currentLevel += 1
    setLevel(currentLevel)
})
function setEnemy(levelNumber: number) {
    if (levelNumber == 1) {
        mazeEnemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        mazeEnemy2 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        mazeEnemy3 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnTile(mazeEnemy, tiles.getTileLocation(9, 6))
        tiles.placeOnTile(mazeEnemy2, tiles.getTileLocation(3, 10))
        tiles.placeOnTile(mazeEnemy3, tiles.getTileLocation(11, 8))
    } else {

    }
}
let mazeEnemy3: Sprite = null
let mazeEnemy2: Sprite = null
let mazeEnemy: Sprite = null
let Runner: Sprite = null
let currentLevel = 0
setLevel(1)
setEnemy(1)
setRunner()